### ISSUE TITLE
[Bug]: Swaps with WithDesiredOutput parameter fails

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#804] opened 2023-10-27 07:59 UTC
### Steps to reproduce

1. Execute swap call 
0x1a0000000000020000000000000000000000000000000000000000000000000000000000000002000500000000000000000000000000000000000000000000000000000000000100e40b5402000000000000000000000000407a10f35a000000000000000000000000

### Actual behavior

<img width="651" alt="Screenshot 2023-10-27 at 09 56 31" src="https://github.com/sora-xor/sora2-network/assets/17094492/b57e8c5b-91a1-49d2-b50a-d92f238e744c">
<img width="285" alt="Screenshot 2023-10-27 at 09 53 32" src="https://github.com/sora-xor/sora2-network/assets/17094492/21071461-3b99-4ce9-847f-1271dd77fa4b">

### Expected behavior

Swap works with input and output parameters

### Environment

{"label"=>"Development"}

**Comment by bragov4ik** [comment] 2023-10-30 09:54
So the problem is, as expected, in too large weight value. `swap` extrinsic weight turned out to be larger than some allowed amount, which resulted in such errors. Computations of weight for the extrinsic consider weights of the liquidity sources, one of which is order book. Weights for the order book were updated in https://github.com/sora-xor/sora2-network/pull/734, which most likely resulted in the bug appearing.

Originally, the limits for order execution were chosen to easily fit into the block (with lots of room for error). However, the way current `exchange_single_order` benchmarking works seems to use up the provided error margin.

My hypothesis is the following: previous benchmarking (on many orders at once) was calculating worst case more accurately. On the executions, some actions are performed once independent to the number of orders involved (let's say they take time $t_{\text{once}}$), whilst others are repeated for each order: $N \cdot t_{\text{each}}$ ($N$ - number of orders executed).

The original benchmarking calculated the total time correctly:
$$t_1 = t_{\text{once}} + N \cdot t_{\text{each}}$$

Current approach computes total time for single order:
$$t_2' = t_{\text{once}} + t_{\text{each}}$$
Which is later extrapolated into the number of orders:
$$t_2 = N \cdot t_2' = N \cdot t_{\text{once}} + N \cdot t_{\text{each}}$$
resulting in latter being larger than expected:
$$t_2 - t_1 = (N-1) \cdot t_{\text{once}}$$

**Comment by bragov4ik** [comment] 2023-10-30 10:05
As a temporary workaround, smaller values are going to be set manually. However, it is necessary to iron out the benchmark for `exchange_single_order` before shipping the feature in order to compute accurate weights (https://github.com/sora-xor/sora2-network/issues/809).

**Comment by bragov4ik** [comment] 2023-11-01 11:48
After merging the fix #807 and deploying it on dev environment, the same bug was revealed for similar but different case: swaps that involve 2 order book exchanges. In particular, swap (PSWAP -> VAL) that is internally turned into two exchanges (PSWAP -> XOR, XOR -> VAL), increasing the weight about twice (i.e. it effectively doubles the number of possible orders executed within one block).

This should also be addressed in #809. Meanwhile, the limits that restrict # of orders per exchange are reduced twice (1000 -> 500). This makes sure that in such case two exchanges will (in the worst case) not execute >1000 orders (500 max + 500 max = 1000 max)

**Closed** 2023-11-03 07:54 UTC
Labels: bug, S1-critical
