### ISSUE TITLE
[Feature]: Add additional fee to swap batch extrinsic

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#301] opened 2023-03-03 09:01 UTC
### As a

ADAR

### I want to

Take fees from batch swaps

### So that

-

### Flow

1. User calls swap_batch_transfer extrinsic
2. 0.75% of input asset goes to ADAR account (currently unknown)

**Comment by vovac12** [comment] 2023-03-03 09:02
ADAR account should be constant. We can add it to Config of liquidity-proxy pallet

**Comment by pakrentos** [comment] 2023-03-10 10:29
#325 
TODO:
- [ ] Add ADAR commission to swap_transfer_batch
- [ ] Refactor
- [ ] Add new tests

**Comment by pakrentos** [comment] 2023-03-10 10:29
#325 
TODO:
- [ ] Add ADAR commission to swap_transfer_batch
- [ ] Refactor
- [ ] Add new tests

**Comment by pakrentos** [comment] 2023-03-16 09:15
Duplicate of the #323

**Closed by pakrentos** 2023-03-16 09:15 UTC
Labels: feature, ADAR
